#coreKtx = { group = "", name = "", version = "" }
[versions]
androidV= "1.4.0"

[libraries]
coreKtx     = { group = "androidx.core",               name = "core-ktx",      version = "1.7.0"         }
appcompat   = { group = "androidx.appcompat",          name = "appcompat",     version.ref = "androidV"  }
material    = { group = "com.google.android.material", name = "material",      version.ref = "androidV"  }
junit       = { group = "junit",                       name = "junit",         version = "4.13.2"        }
androidTest = { group = "androidx.test.ext",           name = "junit",         version = "1.1.3"         }
espresso    = { group = "androidx.test.espresso",      name = "espresso-core", version = "3.4.0"         }

[bundles]
base = [
    "coreKtx",
    "appcompat"
]